### ISSUE TITLE
License

### ISSUE THREAD

**Issue by djuretic** [gpincheiraa/number2words#7]
Hola, ¿qué licencia tiene el código? (por ejemplo, MIT).
Convendría poner un archivo LICENSE.md clarificando la licencia.
Gracias de antemano.

**Comment by gpincheiraa** [comment]
Muy buena idea, tienes alguna idea de un formato *tipo* de una licencia?

**Comment by djuretic** [comment]
Github tiene un sitio así: http://choosealicense.com/

**Comment by gpincheiraa** [comment]
Gracias por tu aporte, ya he agregado la licencia. Cerraré este issue.
